export const MENU_PARSER_SELECTORS = {
	section: [
		'[class*="DefaultView_section__"]',
	],
	sectionName: [
		'[class*="DefaultView_sectionTitle"]',
	],
	sectionNav: [
		'[class*="styles_sectionListItem"]',
	],
	category: [
		'[class*="DefaultView_categoryWrapper"]',
		'[data-menu-category]',
		'[data-category]',
		'.menu-category',
		'.category',
		'section',
	],
	categoryName: [
		'[class*="DefaultView_categoryName"]',
		'[data-category-name]',
		'.category-title',
		'.menu-category__title',
		'h2',
		'h3',
	],
	categoryDescription: [
		'[data-category-description]',
		'.category-description',
		'.menu-category__description',
	],
	dish: [
		'.section-list-item[data-url]',
		'[class*="MenuItemInner_menuItem"][data-url]',
		'[data-menu-item]',
		'[data-product]',
		'.menu-item',
		'.dish',
		'.product',
		'article',
	],
	dishName: [
		'[class*="MenuItemInner_menu-item-title"]',
		'[data-item-name]',
		'[data-product-name]',
		'.menu-item__title',
		'.dish-title',
		'.product-title',
		'h3',
		'h4',
	],
	dishDescription: [
		'[class*="MenuItemInner_menu-item-description"] pre',
		'[class*="MenuItemInner_menu-item-description"]',
		'[data-item-description]',
		'[data-product-description]',
		'.menu-item__description',
		'.dish-description',
		'.product-description',
		'p',
	],
	price: [
		'[data-price]',
		'[class*="MenuItemInner_menu-item-price"]',
		'[class*="PriceDiscount"]',
		'[data-price]',
		'.price',
		'.menu-item__price',
		'.dish-price',
		'.product-price',
	],
	weight: [
		'[class*="styles_menu-label"]',
		'[data-weight]',
		'[data-portion]',
		'.weight',
		'.portion',
		'.menu-item__weight',
	],
	image: [
		'picture source[srcset]',
		'[class*="MenuItemInner_previewImage"]',
		'img[data-src]',
		'img[src]',
		'[data-image]',
	],
	allergens: [
		'[data-allergens]',
		'.allergens',
		'.dish-allergens',
	],
	calories: [
		'[data-calories]',
		'.calories',
		'.dish-calories',
	],
	cookingTime: [
		'[data-cooking-time]',
		'.cooking-time',
		'.dish-cooking-time',
	],
};
